# How traces are transferred through containers:
# App traces-> OTLP -> Jaeger
version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    deploy:
      resources:
        limits:
          memory: 512M
  otel-collector:
    image: otel/opentelemetry-collector
    command: [ "--config=/mnt/otel/otel-collector-config.yml" ]
    volumes:
      - ./otel:/mnt/otel/
    ports:
#      - "1888:1888"   # pprof extension
#      - "8888:8888"   # Prometheus' metrics exposed by the collector
#      - "8889:8889"   # Prometheus exporter metrics
#      - "55679:55679" # zpages extension
      - "13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger
  transloapi:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - otel-collector
    ports:
      - "80:80"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - ./redis-data:/data
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    deploy:
      resources:
        limits:
          memory: 512M
